version: '3'

services:
  django_rest_api:
    container_name: django_rest_api
    image: local/django_rest_api
    build:
      context: ./backend
      args:
        - UID
        - GID
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/home/app/rest_api
      - /mnt/nanodqmio:/mnt/nanodqmio
    command: bash -c 'cd mlplayground && python3 manage.py runserver 0.0.0.0:8000'
    network_mode: "host"

  django_celery_worker1:
    container_name: django_celery_worker1
    image: local/django_rest_api
    volumes:
      - ./backend/:/home/app/rest_api
      - /mnt/nanodqmio:/mnt/nanodqmio
    command: bash -c 'cd mlplayground && celery -A mlplayground worker -l INFO -c 1 -n worker1 -Q dqmio_file_indexer_queue'
    entrypoint: ''
    depends_on:
      - django_rest_api
    network_mode: "host"

  django_celery_worker2:
    container_name: django_celery_worker2
    image: local/django_rest_api
    volumes:
      - ./backend/:/home/app/rest_api
      - /mnt/nanodqmio:/mnt/nanodqmio
    command: bash -c 'cd mlplayground && celery -A mlplayground worker -l INFO -c 1 -n worker2 -Q dqmio_etl_queue'
    entrypoint: ''
    depends_on:
      - django_rest_api
    network_mode: "host"

  django_celery_beat:
    container_name: django_celery_beat
    image: local/django_rest_api
    volumes:
      - ./backend/:/home/app/rest_api
      - /mnt/nanodqmio:/mnt/nanodqmio
    command: bash -c 'cd mlplayground && celery -A mlplayground beat -l INFO'
    entrypoint: ''
    depends_on:
      - django_rest_api
    network_mode: "host"

  react_frontend:
    container_name: react_frontend
    image: react_frontend
    build:
      context: ./frontend
      args:
        - UID
        - GID
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/home/app/web
    command: bash -c "yarn run start"
    depends_on:
      - django_rest_api
    network_mode: "host"
