version: '3'

services:
  api:
    build: ./backend
    ports:
      - 8000:8000/
    volumes:
      - ./backend/:/api
      - /mnt/nanodqmio:/mnt/nanodqmio
    command: bash -c "cd mlplayground && poetry run python manage.py runserver 0.0.0.0:8000"
    network_mode: "host"

  api_worker1:
    build: ./backend
    volumes:
      - ./backend/:/api
      - /mnt/nanodqmio:/mnt/nanodqmio
    command: bash -c "cd mlplayground && poetry run celery -A mlplayground worker -l INFO -c 1 -n worker1 -Q dqmio_file_indexer_queue"
    network_mode: "host"

  api_worker2:
    build: ./backend
    volumes:
      - ./backend/:/api
      - /mnt/nanodqmio:/mnt/nanodqmio
    command: bash -c "cd mlplayground && poetry run celery -A mlplayground worker -l INFO -c 1 -n worker2 -Q dqmio_etl_queue"
    network_mode: "host"

  api_beat_schedule:
    build: ./backend
    volumes:
      - ./backend/:/api
      - /mnt/nanodqmio:/mnt/nanodqmio
    command: bash -c "cd mlplayground && poetry run celery -A mlplayground beat -l INFO"
    network_mode: "host"

  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/web/
    command: bash -c "yarn run start"
    network_mode: "host"
