# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
      files: ^backend
    - id: end-of-file-fixer
      files: ^backend
    - id: check-yaml
      files: ^backend
    - id: check-added-large-files
      files: ^backend
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    - id: black
      files: ^backend
      args: [
        --line-length=120
      ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      files: ^backend
      additional_dependencies: [flake8-bugbear]
      args: [
        --max-line-length=120,
        --max-complexity=10
      ]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
    - id: isort
      files: ^backend
      args: [
        --atomic,
        --profile=black,
        --line-length=120,
        --skip-gitignore
      ]
