kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: cms-dials-prod
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: dials
    app.openshift.io/runtime: nginx
    app.openshift.io/runtime-namespace: cms-dials-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        deployment: frontend
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 256Mi
          ports:
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always
          image: >-
            image-registry.openshift-image-registry.svc:5000/cms-dials-prod/frontend:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
