kind: Deployment
apiVersion: apps/v1
metadata:
  name: common-redbeat
  namespace: cms-dials-prod
  labels:
    app: common-redbeat
    app.kubernetes.io/component: common-redbeat
    app.kubernetes.io/instance: common-redbeat
    app.kubernetes.io/name: common-redbeat
    app.kubernetes.io/part-of: common-etl
    app.openshift.io/runtime: python
    app.openshift.io/runtime-namespace: cms-dials-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-redbeat
  template:
    metadata:
      labels:
        app: common-redbeat
        deployment: common-redbeat
      annotations:
        eos.okd.cern.ch/mount-eos-with-credentials-from-secret: eos-credentials
    spec:
      volumes:
        - name: eos-storage
          persistentVolumeClaim:
            claimName: eos-storage
      initContainers:
        - name: db-init
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 1024Mi
          command:
            - bash
            - '-c'
            - >-
              alembic upgrade head
          envFrom:
            - configMapRef:
                name: dials-etl-configmap
            - secretRef:
                name: dials-etl-secrets
          imagePullPolicy: Always
          image: >-
            image-registry.openshift-image-registry.svc:5000/cms-dials-prod/etl:latest
      containers:
        - name: common-redbeat
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 1024Mi
          command:
            - bash
            - '-c'
            - >-
              celery --app=python beat --loglevel=INFO
              --scheduler redbeat.RedBeatScheduler
          envFrom:
            - configMapRef:
                name: dials-etl-configmap
            - secretRef:
                name: dials-etl-secrets
            - secretRef:
                name: eos-credentials
          imagePullPolicy: Always
          volumeMounts:
            - name: eos-storage
              readOnly: true
              mountPath: /eos
          image: >-
            image-registry.openshift-image-registry.svc:5000/cms-dials-prod/etl:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
