kind: Deployment
apiVersion: apps/v1
metadata:
  name: flower
  namespace: cms-dials-prod
  labels:
    app: flower
    app.kubernetes.io/component: flower
    app.kubernetes.io/instance: flower
    app.kubernetes.io/name: flower
    app.kubernetes.io/part-of: common-etl
    app.openshift.io/runtime: python
    app.openshift.io/runtime-namespace: cms-dials-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
        deployment: flower
    spec:
      volumes:
        - name: eos-storage
          persistentVolumeClaim:
            claimName: eos-storage
      containers:
        - name: flower
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 1024Mi
          command:
            - bash
            - '-c'
            - >-
              celery --app=python flower --purge_offline_workers=120
          envFrom:
            - configMapRef:
                name: dials-etl-configmap
            - secretRef:
                name: dials-etl-secrets
            - secretRef:
                name: eos-credentials
          imagePullPolicy: Always
          image: >-
            image-registry.openshift-image-registry.svc:5000/cms-dials-prod/etl:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
