kind: Deployment
apiVersion: apps/v1
metadata:
  name: common-indexer
  namespace: cms-dials-prod
  labels:
    app: common-indexer
    app.kubernetes.io/component: common-indexer
    app.kubernetes.io/instance: common-indexer
    app.kubernetes.io/name: common-indexer
    app.kubernetes.io/part-of: common-etl
    app.openshift.io/runtime: python
    app.openshift.io/runtime-namespace: cms-dials-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-indexer
  template:
    metadata:
      labels:
        app: common-indexer
        deployment: common-indexer
      annotations:
        eos.okd.cern.ch/mount-eos-with-credentials-from-secret: eos-credentials
    spec:
      volumes:
        - name: eos-storage
          persistentVolumeClaim:
            claimName: eos-storage
      containers:
        - name: common-indexer
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 2048Mi
          command:
            - bash
            - '-c'
            - >-
              celery --app=python worker --loglevel=INFO --concurrency=1
              --autoscale=1,0 --max-tasks-per-child=1 --hostname=common-indexer@%h
              --queues=common-indexer
          envFrom:
            - configMapRef:
                name: dials-etl-configmap
            - secretRef:
                name: dials-etl-secrets
            - secretRef:
                name: eos-credentials
          imagePullPolicy: Always
          volumeMounts:
            - name: eos-storage
              readOnly: true
              mountPath: /eos
          image: >-
            image-registry.openshift-image-registry.svc:5000/cms-dials-prod/etl:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
