apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: backend
  namespace: dials-prod
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: gabrielmscampos/dials-backend-base
      from:
        kind: DockerImage
        name: gabrielmscampos/dials-backend-base
      referencePolicy:
        type: Local

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  namespace: dials-prod
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: gabrielmscampos/dials-frontend
      from:
        kind: DockerImage
        name: gabrielmscampos/dials-frontend
      referencePolicy:
        type: Local
