apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: backend
  namespace: cms-dials-prod
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: registry.cern.ch/cms-dqmdc/dials-backend-base
      from:
        kind: DockerImage
        name: registry.cern.ch/cms-dqmdc/dials-backend-base
      referencePolicy:
        type: Local
      pullSecret: cern-registry-credentials

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  namespace: cms-dials-prod
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: registry.cern.ch/cms-dqmdc/dials-frontend
      from:
        kind: DockerImage
        name: registry.cern.ch/cms-dqmdc/dials-frontend
      referencePolicy:
        type: Local
      pullSecret: cern-registry-credentials
