# Note: Fill the secret values encoded as base64

kind: Secret
apiVersion: v1
metadata:
  name: eos-credentials
  namespace: cms-dials-prod
data:
  KEYTAB_PWD:
  KEYTAB_USER:
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: dials-secrets
  namespace: cms-dials-prod
data:
  DJANGO_SECRET_KEY:
  DJANGO_DATABASE_PORT:
  DJANGO_DATABASE_HOST:
  DJANGO_DATABASE_NAME:
  DJANGO_DATABASE_USER:
  DJANGO_DATABASE_PASSWORD:
  DJANGO_CELERY_BROKER_URL:
  DJANGO_DQMIO_STORAGE:
  DJANGO_KEYCLOAK_CONFIDENTIAL_CLIENT_ID:
  DJANGO_KEYCLOAK_PUBLIC_CLIENT_ID:
  DJANGO_KEYCLOAK_API_CLIENTS:
  DJANGO_KEYCLOAK_CONFIDENTIAL_SECRET_KEY:
type: Opaque
